---
- hosts: all

  tasks:
    - name: install latest version of mysql
      apt: name=mysql-server state=latest
      become: yes

    - name: install essentials for  MySQL
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python-dev
          - libmysqlclient-dev
          - python3-pip
          - python3-mysql.connector
          - mydumper
          - mysqltuner
          - python3-pymysql
          - python3-mysqldb
        state: latest
      become: yes

    - name: start mysql
      service:
        name: mysql
        state: started
        enabled: true
      become: yes

    - name: copy content to /etc/mysql/my.cnf
      template:
        src: ./my.cnf
        dest: /etc/mysql/my.cnf
        owner: root
        group: root
        mode: 0644
        backup: true
      become: yes

    - name: restart mysql
      service:
        name: mysql
        state: restarted
        enabled: true
      become: yes
